apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-publication-db
  name: k8s-publication-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-publication-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-publication-db
    spec:
      containers:
        - image: postgres:13
          name: postgres
          imagePullPolicy: Never
          env:
            - name: POSTGRES_USER
              value: "chat"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_DB
              value: "chatdb"
          resources: {}
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata-pvc
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
  labels:
    app: k8s-publication-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
