apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-publication-db
  name: k8s-publication-db
spec:
  ports:
  - name: "5432"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: k8s-publication-db
  type: ClusterIP
status:
  loadBalancer: {}