apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-pay
  name: k8s-pay
spec:
  ports:
  - name: "50055"
    port: 50055
    protocol: TCP
    targetPort: 50055
  selector:
    app: k8s-pay
  type: ClusterIP
status:
  loadBalancer: {}
