apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-publication
  name: k8s-publication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-publication
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-publication
    spec:
      containers:
      - image: publication
        name: publication
        command: ["mvn"]
        args: ["spring-boot:run"]
        imagePullPolicy: Never
        env:
            - name: DB_HOST
              value: "k8s-publication-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "chat"
            - name: DB_PASSWORD
              value: "root"
            - name: DB_NAME
              value: "chatdb"
        resources: {}
status: {}