apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-publication
  name: k8s-publication
spec:
  ports:
  - name: "50051"
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: k8s-publication
  type: ClusterIP
status:
  loadBalancer: {}