apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-pay-db
  name: k8s-pay-db
spec:
  ports:
  - name: "5444"
    port: 5444
    protocol: TCP
    targetPort: 5432
  selector:
    app: k8s-pay-db
  type: ClusterIP
status:
  loadBalancer: {}